# Nama alur kerja (workflow) yang akan ditampilkan di tab "Actions" pada repositori GitHub Anda.
name: Installer for Windows

# Pemicu (Triggers): Mendefinisikan kapan alur kerja ini akan dijalankan secara otomatis.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

# Jobs: Daftar pekerjaan (tasks) yang akan dieksekusi dalam alur kerja ini.
jobs:
  build:
    # 'runs-on' menentukan jenis mesin virtual yang akan digunakan untuk menjalankan pekerjaan ini.
    # 'windows-latest' menjamin lingkungan build yang bersih setiap saat.
    runs-on: windows-latest

    # Steps: Rangkaian langkah-langkah sekuensial yang akan dieksekusi oleh pekerjaan "build".
    steps:
      # Langkah 1: Checkout Kode Sumber
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Mengunduh semua submodule seperti Leptonica.
          submodules: 'recursive'

      # Langkah 2: Menyiapkan Lingkungan MSYS2
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            make
            unzip
            wget
            p7zip

      # Langkah 3: Cache vcpkg untuk mempercepat build
      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: |
            C:/vcpkg
            C:/vcpkg/installed
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-

      # Langkah 4: Setup vcpkg
      - name: Setup vcpkg
        run: |
          if (!(Test-Path "C:/vcpkg")) {
            git clone https://github.com/Microsoft/vcpkg.git C:/vcpkg
            cd C:/vcpkg
            ./bootstrap-vcpkg.bat
          }
          echo "C:/vcpkg" >> $env:GITHUB_PATH
        shell: pwsh

      # Langkah 5: Setup Ninja build system
      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      # Langkah 6: Instal Dependensi Menggunakan vcpkg (diperbaiki nama package)
      - name: Install dependencies via vcpkg
        run: |
          vcpkg install leptonica:x64-windows
          vcpkg install libarchive:x64-windows
          vcpkg install curl:x64-windows
          vcpkg install icu:x64-windows
        shell: pwsh

      # Langkah 7: Mengkonfigurasi Proyek dengan CMake
      - name: Configure CMake
        run: >
          cmake -G Ninja -S . -B build
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
          -DBUILD_TRAINING_TOOLS=ON

      # Langkah 8: Mengkompilasi Kode dan Menjalankan Instalasi
      - name: Build
        run: cmake --build build --config Release --target install

      # Langkah 9: Menginstal NSIS (Alat Pembuat Installer)
      - name: Install NSIS
        run: choco install nsis -y

      # Langkah 10: Menjalankan Skrip untuk Membuat Installer .exe
      - name: Build installer
        shell: msys2 {0}
        run: bash nsis/build.sh

      # Langkah 11: Mengunggah Installer sebagai "Artifact"
      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: tesseract-ocr-installer-windows
          path: nsis/tesseract-ocr-*.exe
