# Nama alur kerja (workflow) yang akan ditampilkan di tab "Actions" pada repositori GitHub Anda.
name: Installer for Windows

# Pemicu (Triggers): Mendefinisikan kapan alur kerja ini akan dijalankan secara otomatis.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

# Jobs: Daftar pekerjaan (tasks) yang akan dieksekusi dalam alur kerja ini.
jobs:
  build:
    # 'runs-on' menentukan jenis mesin virtual yang akan digunakan untuk menjalankan pekerjaan ini.
    # 'windows-latest' menjamin lingkungan build yang bersih setiap saat.
    runs-on: windows-latest

    # Steps: Rangkaian langkah-langkah sekuensial yang akan dieksekusi oleh pekerjaan "build".
    steps:
      # Langkah 1: Checkout Kode Sumber
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Mengunduh semua submodule seperti Leptonica.
          submodules: 'recursive'

      # Langkah 2: Menyiapkan Lingkungan MSYS2
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            make
            unzip
            wget
            p7zip

      # Langkah 3: Mengunduh dan Menyiapkan vcpkg Secara Manual
      - name: Clone and Update vcpkg
        run: |
          echo "Cloning vcpkg..."
          git clone https://github.com/microsoft/vcpkg.git D:/a/vcpkg
          echo "Bootstrapping vcpkg..."
          D:/a/vcpkg/bootstrap-vcpkg.bat
          echo "Updating vcpkg ports registry..."
          cd D:/a/vcpkg
          git pull
        shell: cmd

      # Langkah 4: Menambahkan vcpkg ke PATH
      - name: Add vcpkg to PATH
        run: echo "D:\a\vcpkg" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh

      # Langkah 5: Instal Dependensi Menggunakan vcpkg
      - name: Install dependencies via vcpkg
        run: vcpkg install leptonica libarchive libcurl icu --triplet x64-windows

      # Langkah 6: Mengkonfigurasi Proyek dengan CMake
      - name: Configure CMake
        run: >
          cmake -G Ninja -S . -B build
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_TOOLCHAIN_FILE=D:/a/vcpkg/scripts/buildsystems/vcpkg.cmake
          -DBUILD_TRAINING_TOOLS=ON

      # Langkah 7: Mengkompilasi Kode dan Menjalankan Instalasi
      - name: Build
        run: cmake --build build --config Release --target install

      # Langkah 8: Menginstal NSIS (Alat Pembuat Installer)
      - name: Install NSIS
        run: choco install nsis -y

      # Langkah 9: Menjalankan Skrip untuk Membuat Installer .exe
      - name: Build installer
        shell: msys2 {0}
        run: bash nsis/build.sh

      # Langkah 10: Mengunggah Installer sebagai "Artifact"
      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: tesseract-ocr-installer-windows
          path: nsis/tesseract-ocr-*.exe
